### PR TITLE
fix: fix win32 detection

### PR DESCRIPTION
**Pull request by ww-daniel-mora**
* Introduce a util function to check for win32 in vim.fn correctly
* Replace all checks for win32 with the new function

### CODE REVIEW

**Review by jcdickinson — APPROVED** [review]
Lgtm, thanks for the contribution!

**Comment by ww-daniel-mora** [comment]
Can you post `:lua =vim.fn` 
Then we can make a more robust check

**Comment by WillEhrendreich** [comment]
@ww-daniel-mora what do you mean? literally give the output of :lua = vim.fn? that's this:

{
  argc = <function 1>,
  bufadd = <function 2>,
  bufload = <function 3>,
  bufloaded = <function 4>,
  bufname = <function 5>,
  bufwinid = <function 6>,
  bufwinnr = <function 7>,
  col = <function 8>,
  confirm = <function 9>,
  environ = <function 10>,
  escape = <function 11>,
  executable = <function 12>,
  execute = <function 13>,
  exepath = <function 14>,
  exists = <function 15>,
  expand = <function 16>,
  filereadable = <function 17>,
  fnameescape = <function 18>,
  fnamemodify = <function 19>,
  foldclosed = <function 20>,
  foldclosedend = <function 21>,
  getbufinfo = <function 22>,
  getchar = <function 23>,
  getcharstr = <function 24>,
  getcmdline = <function 25>,
  getcmdpos = <function 26>,
  getcmdtype = <function 27>,
  getcmdwintype = <function 28>,
  getcompletion = <function 29>,
  getcurpos = <function 30>,
  getcursorcharpos = <function 31>,
  getcwd = <function 32>,
  getenv = <function 33>,
  getftime = <function 34>,
  getline = <function 35>,
  gettabinfo = <function 36>,
  glob = <function 37>,
  has = <function 38>,
  hlID = <function 39>,
  hlexists = <function 40>,
  indent = <function 41>,
  inputlist = <function 42>,
  isdirectory = <function 43>,
  jobstart = <function 44>,
  jobstop = <function 45>,
  jobwait = <function 46>,
  json_decode = <function 47>,
  json_encode = <function 48>,
  line = <function 49>,
  localtime = <function 50>,
  maparg = <function 51>,
  mapcheck = <function 52>,
  match = <function 53>,
  matchlist = <function 54>,
  mkdir = <function 55>,
  mode = <function 56>,
  nextnonblank = <function 57>,
  prevnonblank = <function 58>,
  prompt_setprompt = <function 59>,
  pumvisible = <function 60>,
  reg_executing = <function 61>,
  reg_recording = <function 62>,
  screencol = <function 63>,
  screenpos = <function 64>,
  screenrow = <function 65>,
  setenv = <function 66>,
  setwinvar = <function 67>,
  sha256 = <function 68>,
  shiftwidth = <function 69>,
  sign_define = <function 70>,
  sign_getdefined = <function 71>,
  sign_getplaced = <function 72>,
  sign_placelist = <function 73>,
  sign_unplace = <function 74>,
  split = <function 75>,
  stdpath = <function 76>,
  strcharpart = <function 77>,
  strchars = <function 78>,
  strdisplaywidth = <function 79>,
  strftime = <function 80>,
  strlen = <function 81>,
  substitute = <function 82>,
  synID = <function 83>,
  synIDattr = <function 84>,
  synIDtrans = <function 85>,
  synstack = <function 86>,
  tabpagenr = <function 87>,
  tempname = <function 88>,
  toupper = <function 89>,
  virtcol = <function 90>,
  win_findbuf = <function 91>,
  win_gettype = <function 92>,
  winheight = <function 93>,
  winlayout = <function 94>,
  winrestview = <function 95>,
  winsaveview = <function 96>,
  <metatable> = {
    __index = <function 97>
  }
}

**Comment by ww-daniel-mora** [comment]
Thank you @WillEhrendreich that's exactly what I wanted. That `has` check is always returning true and "win32" is obviously not a meaningful thing to check on anyways since it does not show up in your vim.fn table either. Let me see if we determine platform another way and update the check.

**Comment by ww-daniel-mora** [comment]
I asked in you pr as well but can you post the output of this call as well
`:lua =vim.loop.os_uname().sysname`

**Pull request merged**
