### PR TITLE
Update auth-menu.lua

### PR DESCRIPTION
**Pull request by rgzntrade**
it should be vim.ui.input

### CODE REVIEW

**Review by PreetamSing — CHANGES_REQUESTED** [review]
I guess `input` won't be a solution here as it doesn't conceal the user input. We can change the definition of `get_key` function with following code.
```lua
local function get_key(callback)
    vim.fn.inputsecret({
        prompt = "Token ",
        on_submit = callback,
    })
end
```
What do you think?

**Comment by WillEhrendreich** [comment]
@PreetamSing that's not gonna work. 

as of NVIM v0.10.0-dev-422+g68e2d7229 , it's not integrated or something.
point of the matter is this is a breaking change, and I've had to do what the pr here did to get it working. https://github.com/neovim/neovim/pull/19413

**Comment by rgzntrade** [comment]
You are right, but with the stable version（0.9.1）, inputsecert does not work yet. Please consider compatibility

**Comment by PreetamSing** [comment]
@WillEhrendreich @rgzntrade I'm able to use `inputsecret` function in **`NVIM v0.8.3`** as well as in **`NVIM v0.9.1`**.  

Maybe you're trying to use that function from `vim.ui` module. Try accessing it from `vim.fn` path, as written in my initial suggestion code. Or you can also run `:help inputsecret` command for more info.  

Let me know if I'm misunderstanding something.

**Comment by WillEhrendreich** [comment]
ah, ok. yep. you're right @PreetamSing, the fn vs ui thing was getting in the way. works great on my end with what's in the pr. thanks!

**Comment by aerosol** [comment]
[963c460](https://github.com/jcdickinson/codeium.nvim/commit/963c4604b52470d9e904a0e6e8421fffa8686d52) works for me with neovim 0.9.1 - could not get the token prompt when on main. Thanks!

**Comment by WillEhrendreich** [comment]
I take it back, that code does not work, I had to go back to vim.ui.input, because it doesn't save the auth for some reason otherwise

**Comment by rgzntrade** [comment]
>  
	[C]: in function 'inputsecret'
	...vim_up/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:5: in function 'get_key'
	...vim_up/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:100: in function 'callback'
	...vim_up/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:122: in function 'on_choice'
	.../nvim_up/lazy/dressing.nvim/lua/dressing/select/init.lua:78: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

This will create a new error

**Pull request closed without merging**
