### PR TITLE
Use `inputsecret` for token

### PR DESCRIPTION
**Pull request by mrshmllow**

### CODE REVIEW

**Comment by jcdickinson** [comment]
Thanks for the contribution!

**Comment by Koalhack** [comment]
Hello, I updated today with your new merge via Lazy.nvim and before changing `input` for `inputsecret`, the authentication system worked, now on Windows I get the following error, i don't know if this is normal or not for Windows.

image


image

INFO: 
OS : Windows 10
Terminal : Windows Terminal V1.17
Neovim Version : 0.9.1

**Comment by 00sapo** [comment]
Same thing here

**Comment by mrshmllow** [comment]
It should be `vim.fn.inputsecret`

**Comment by 00sapo** [comment]
> It should be `vim.fn.inputsecret`

Could you commit to this branch so I can update my config?

**Comment by mrshmllow** [comment]
I fixed this branch, but the owner might have to help manually

**Comment by 00sapo** [comment]
Thanks!

**Comment by mrshmllow** [comment]
@jcdickinson Was this ever resolved?

**Pull request merged**
